var script1 = birthstoneGemFinder();
script1.initiation();
var script2 = zodiacFinder();
script2.initiation2();
var script3 = pageReload();
script3.initiation3();
var script4 = loadCheck();
script4.initiation4();
var script5 = giveFeedback();
script5.initiation5();